name: publish-adapter-basketball
on:
  push:
    tags: ['v*.*.*']   # e.g. v1.0.0
permissions:
  contents: read
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'
      - name: Install deps (needs packages: read)
        run: pnpm install --frozen-lockfile
        env: { NODE_AUTH_TOKEN: ${{ github.token }} }
      - run: pnpm build
      - name: Publish
        run: pnpm publish --access public --no-git-checks
        env: { NODE_AUTH_TOKEN: ${{ github.token }} }
